/**
 *
 * Programa diseñado integramente para la empresa BPSA por Cardenal Bridge Company
 *
 */
package bpsa;

import de.javasoft.plaf.synthetica.SyntheticaPlainLookAndFeel;
import java.awt.Image;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author alanantonio
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main, Constantes para una mejor modificación del
     * sistema.
     */
    public final boolean SIEMPREENCIMA = true;
    public final boolean MODIFICARTAMAÑO = false;
    public final String ICONO = "src/image/BPSA.png";
    public final String NOMBRE = "BPSA: Usuario";
    public final String ICOLOGO = "src/image/BPSAnombre.png";
    public final String QUIENESSOMOS = "src/icon/people-8x.png";
    public final String USUARIO = "src/icon/person-8x.png";
    public final String POLITICASDEVENTA = "src/icon/lock-locked-8x.png";
    public final String TERMINOSYCONDICIONES = "src/icon/document-8x.png";
    public final String AYUDA = "src/icon/question-mark-8x.png";
    public final String TELEFONO = "src/icon/bullhorn-8x.png";

    public Main() {
        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel(new SyntheticaPlainLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        properties();
    }

    public void properties() {
        this.setTitle(NOMBRE);
        this.setResizable(MODIFICARTAMAÑO);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setAlwaysOnTop(SIEMPREENCIMA);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ImageIcon icono = new ImageIcon(ICONO);
        this.setIconImage(icono.getImage());
        this.setLocationRelativeTo(null);
        BPSAlogo.setIcon(icon(ICONO, BPSAlogo));
        BPSAicologo.setIcon(icon(ICOLOGO, BPSAicologo));
        IQuienesSomos.setIcon(icon(QUIENESSOMOS, IQuienesSomos));
        IPoliticasdeVenta.setIcon(icon(POLITICASDEVENTA, IPoliticasdeVenta));
        ITerminosyCondiciones.setIcon(icon(TERMINOSYCONDICIONES, ITerminosyCondiciones));
        IAyuda.setIcon(icon(AYUDA, IAyuda));
        Itelefono.setIcon(icon(TELEFONO, Itelefono));
        Usuario.setIcon(icon(USUARIO,Usuario));
    }

    public Icon icon(String ICONO, JLabel a) {
        ImageIcon fot = new ImageIcon(ICONO);
        a.setText("");
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(a.getWidth(), a.getHeight(), Image.SCALE_DEFAULT));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        BPSAlogo = new javax.swing.JLabel();
        BarraBotones2 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        Inferior = new javax.swing.JPanel();
        BPSAicologo = new javax.swing.JLabel();
        AccesosDirecto = new javax.swing.JPanel();
        LigasAdicionales = new javax.swing.JPanel();
        QuienesSomos = new javax.swing.JPanel();
        IQuienesSomos = new javax.swing.JLabel();
        Texto = new javax.swing.JLabel();
        PoliticasdeVenta = new javax.swing.JPanel();
        IPoliticasdeVenta = new javax.swing.JLabel();
        Texto2 = new javax.swing.JLabel();
        TerminosyCondiciones = new javax.swing.JPanel();
        Texto3 = new javax.swing.JLabel();
        ITerminosyCondiciones = new javax.swing.JLabel();
        Contacto = new javax.swing.JPanel();
        Ayuda2 = new javax.swing.JPanel();
        IAyuda = new javax.swing.JLabel();
        Texto4 = new javax.swing.JLabel();
        Telefono = new javax.swing.JPanel();
        Itelefono = new javax.swing.JLabel();
        Texto7 = new javax.swing.JLabel();
        BarraBotones = new javax.swing.JPanel();
        Ayuda = new javax.swing.JButton();
        Inicio = new javax.swing.JButton();
        BarraBotones1 = new javax.swing.JPanel();
        Articuloes = new javax.swing.JButton();
        Solicitudes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        BPSAlogo.setText("BPSALogo");
        BPSAlogo.setAlignmentY(0.0F);

        Usuario.setText("Usuario");
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BarraBotones2Layout = new javax.swing.GroupLayout(BarraBotones2);
        BarraBotones2.setLayout(BarraBotones2Layout);
        BarraBotones2Layout.setHorizontalGroup(
            BarraBotones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraBotones2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Usuario))
        );
        BarraBotones2Layout.setVerticalGroup(
            BarraBotones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BPSAicologo.setText("jLabel1");

        AccesosDirecto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        LigasAdicionales.setBorder(javax.swing.BorderFactory.createTitledBorder("Ligas Adicionales"));

        QuienesSomos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        QuienesSomos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        IQuienesSomos.setText("Icono");

        Texto.setText("¿Quienes Somos?");

        javax.swing.GroupLayout QuienesSomosLayout = new javax.swing.GroupLayout(QuienesSomos);
        QuienesSomos.setLayout(QuienesSomosLayout);
        QuienesSomosLayout.setHorizontalGroup(
            QuienesSomosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuienesSomosLayout.createSequentialGroup()
                .addComponent(IQuienesSomos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        QuienesSomosLayout.setVerticalGroup(
            QuienesSomosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuienesSomosLayout.createSequentialGroup()
                .addGroup(QuienesSomosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Texto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(IQuienesSomos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PoliticasdeVenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PoliticasdeVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        IPoliticasdeVenta.setText("Icono");

        Texto2.setText("Politicas de Venta");

        javax.swing.GroupLayout PoliticasdeVentaLayout = new javax.swing.GroupLayout(PoliticasdeVenta);
        PoliticasdeVenta.setLayout(PoliticasdeVentaLayout);
        PoliticasdeVentaLayout.setHorizontalGroup(
            PoliticasdeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoliticasdeVentaLayout.createSequentialGroup()
                .addComponent(IPoliticasdeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PoliticasdeVentaLayout.setVerticalGroup(
            PoliticasdeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoliticasdeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(IPoliticasdeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TerminosyCondiciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TerminosyCondiciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Texto3.setText("Terminos y Condiciones");

        ITerminosyCondiciones.setText("Icono");

        javax.swing.GroupLayout TerminosyCondicionesLayout = new javax.swing.GroupLayout(TerminosyCondiciones);
        TerminosyCondiciones.setLayout(TerminosyCondicionesLayout);
        TerminosyCondicionesLayout.setHorizontalGroup(
            TerminosyCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TerminosyCondicionesLayout.createSequentialGroup()
                .addComponent(ITerminosyCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TerminosyCondicionesLayout.setVerticalGroup(
            TerminosyCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TerminosyCondicionesLayout.createSequentialGroup()
                .addGroup(TerminosyCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ITerminosyCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout LigasAdicionalesLayout = new javax.swing.GroupLayout(LigasAdicionales);
        LigasAdicionales.setLayout(LigasAdicionalesLayout);
        LigasAdicionalesLayout.setHorizontalGroup(
            LigasAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LigasAdicionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LigasAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuienesSomos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PoliticasdeVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TerminosyCondiciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LigasAdicionalesLayout.setVerticalGroup(
            LigasAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LigasAdicionalesLayout.createSequentialGroup()
                .addComponent(QuienesSomos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PoliticasdeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TerminosyCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Contacto.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto"));

        Ayuda2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Ayuda2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        IAyuda.setText("Icono");

        Texto4.setText("Ayuda");

        javax.swing.GroupLayout Ayuda2Layout = new javax.swing.GroupLayout(Ayuda2);
        Ayuda2.setLayout(Ayuda2Layout);
        Ayuda2Layout.setHorizontalGroup(
            Ayuda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ayuda2Layout.createSequentialGroup()
                .addComponent(IAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Texto4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Ayuda2Layout.setVerticalGroup(
            Ayuda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Texto4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(IAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Telefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Itelefono.setText("Icono");

        Texto7.setText("+52(442)24494976");

        javax.swing.GroupLayout TelefonoLayout = new javax.swing.GroupLayout(Telefono);
        Telefono.setLayout(TelefonoLayout);
        TelefonoLayout.setHorizontalGroup(
            TelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelefonoLayout.createSequentialGroup()
                .addComponent(Itelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Texto7, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
        );
        TelefonoLayout.setVerticalGroup(
            TelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelefonoLayout.createSequentialGroup()
                .addGroup(TelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(Itelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout ContactoLayout = new javax.swing.GroupLayout(Contacto);
        Contacto.setLayout(ContactoLayout);
        ContactoLayout.setHorizontalGroup(
            ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactoLayout.createSequentialGroup()
                        .addComponent(Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(ContactoLayout.createSequentialGroup()
                        .addComponent(Ayuda2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        ContactoLayout.setVerticalGroup(
            ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ayuda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout AccesosDirectoLayout = new javax.swing.GroupLayout(AccesosDirecto);
        AccesosDirecto.setLayout(AccesosDirectoLayout);
        AccesosDirectoLayout.setHorizontalGroup(
            AccesosDirectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccesosDirectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LigasAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AccesosDirectoLayout.setVerticalGroup(
            AccesosDirectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccesosDirectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccesosDirectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Contacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LigasAdicionales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InferiorLayout = new javax.swing.GroupLayout(Inferior);
        Inferior.setLayout(InferiorLayout);
        InferiorLayout.setHorizontalGroup(
            InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InferiorLayout.createSequentialGroup()
                .addGroup(InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InferiorLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(BPSAicologo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InferiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AccesosDirecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InferiorLayout.setVerticalGroup(
            InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InferiorLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(BPSAicologo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(AccesosDirecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Ayuda.setText("Ayuda");

        Inicio.setText("Inicio");

        javax.swing.GroupLayout BarraBotonesLayout = new javax.swing.GroupLayout(BarraBotones);
        BarraBotones.setLayout(BarraBotonesLayout);
        BarraBotonesLayout.setHorizontalGroup(
            BarraBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BarraBotonesLayout.setVerticalGroup(
            BarraBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        Articuloes.setText("Articulos");
        Articuloes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArticuloesActionPerformed(evt);
            }
        });

        Solicitudes.setText("Solicitudes");
        Solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitudesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraBotones1Layout = new javax.swing.GroupLayout(BarraBotones1);
        BarraBotones1.setLayout(BarraBotones1Layout);
        BarraBotones1Layout.setHorizontalGroup(
            BarraBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraBotones1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Articuloes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        BarraBotones1Layout.setVerticalGroup(
            BarraBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraBotones1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Articuloes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Solicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainLayout.createSequentialGroup()
                        .addComponent(Inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(MainLayout.createSequentialGroup()
                        .addComponent(BarraBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainLayout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(BPSAlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(324, 324, 324))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BarraBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BarraBotones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BarraBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarraBotones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarraBotones2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(BPSAlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitudesActionPerformed
        Solicitudes solicitudes = new Solicitudes();
        solicitudes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SolicitudesActionPerformed

    private void ArticuloesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArticuloesActionPerformed
        Articulos articulos = new Articulos();
        articulos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ArticuloesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccesosDirecto;
    private javax.swing.JButton Articuloes;
    private javax.swing.JButton Ayuda;
    private javax.swing.JPanel Ayuda2;
    private javax.swing.JLabel BPSAicologo;
    private javax.swing.JLabel BPSAlogo;
    private javax.swing.JPanel BarraBotones;
    private javax.swing.JPanel BarraBotones1;
    private javax.swing.JPanel BarraBotones2;
    private javax.swing.JPanel Contacto;
    private javax.swing.JLabel IAyuda;
    private javax.swing.JLabel IPoliticasdeVenta;
    private javax.swing.JLabel IQuienesSomos;
    private javax.swing.JLabel ITerminosyCondiciones;
    private javax.swing.JPanel Inferior;
    private javax.swing.JButton Inicio;
    private javax.swing.JLabel Itelefono;
    private javax.swing.JPanel LigasAdicionales;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel PoliticasdeVenta;
    private javax.swing.JPanel QuienesSomos;
    private javax.swing.JButton Solicitudes;
    private javax.swing.JPanel Telefono;
    private javax.swing.JPanel TerminosyCondiciones;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JLabel Texto4;
    private javax.swing.JLabel Texto7;
    private javax.swing.JLabel Usuario;
    // End of variables declaration//GEN-END:variables
}
